version: "3.9"
services:
  php:
    build:
      context: ./Docker/php
    volumes:
      - .:/var/www
    environment:
      - "APP_ENV=local"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
