version: "3.9"
services:
  php:
    build:
      context: ./Docker/php
    volumes:
      - .:/var/www
    environment:
      APP_ENV: local
      DATABASE_PWD: ${DATABASE_PWD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      DATABASE_DSN: ${DATABASE_DSN}

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: mariadb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PWD}
      MYSQL_DATABASE: ${DATABASE_NAME}

volumes:
  db-data: