version: "3.9"
services:
  php:
    build:
      context: ./Docker/php
    volumes:
      - .:/var/www
    environment:
      DATABASE_PASSWORD: verysecret

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: mariadb:10.10
    environment:
      MYSQL_DATABASE: reshome
      MYSQL_ROOT_PASSWORD: veryverysecret